### ISSUE TITLE
PixiJS doesn't work on Linux when using Firefox and the Mesa driver

### ISSUE THREAD

**Issue by klausenbusk** [airmash-refugees/airmash-frontend#18]
Hi

Airmash does not currently work on Linux when using Firefox and the Mesa graphics driver, this is due to a very old [workaround](https://hg.mozilla.org/mozilla-central/rev/8bf32bc47aa2) in the Firefox code. The workaround will probably be removed [soonish](https://bugzilla.mozilla.org/show_bug.cgi?id=1601682), but would it make sense to add a workaround for the time being?

According to this https://github.com/pixijs/pixi.js/issues/4478 issue, specifying:
```
PIXI.settings.SPRITE_MAX_TEXTURES = Math.min(PIXI.settings.SPRITE_MAX_TEXTURES , 16);
```
should be enough.

**Comment by congratulatio** [comment]
Thanks for reporting this, I made a change in https://github.com/airmash-refugees/airmash-frontend/commit/11c1feafbfbb008505e2114996cc491b91cfc73b to retry with `SPRITE_MAX_TEXTURES` set to 16 if initialising `PIXI.WebGLRenderer` fails.

Please could you try https://test.airmash.online to see if this works? If it does I'll push the change out to https://airmash.online.

**Comment by klausenbusk** [comment]
> Thanks for reporting this, I made a change in [11c1fea](https://github.com/airmash-refugees/airmash-frontend/commit/11c1feafbfbb008505e2114996cc491b91cfc73b) to retry with `SPRITE_MAX_TEXTURES` set to 16 if initialising `PIXI.WebGLRenderer` fails.
> 
> Please could you try https://test.airmash.online to see if this works? If it does I'll push the change out to https://airmash.online.

https://test.airmash.online seems to work perfectly. Thanks!

**Comment by congratulatio** [comment]
No problem! I've updated https://airmash.online with the fix.
