### ISSUE TITLE
Vectors on a Network?

### ISSUE THREAD

**Issue by clark-stevenson** [airmash-refugees/airmash-frontend#19]
Hey its real life Scotland 🗡 

I have spent many dozens of hours on this front end code and for me personally, it is impossible.  I am not happy to tweak it, I want to own it fully entirely.  

Can we take a second to appreciate Wight? 👏 

In my build (which doesn't work), I deleted all of my `command` interfaces, and replaced it with his (as it's all exported).  No errors.  (wow!).  So I know my build is running typesafe on the network.  It is a validation we ended up with the same network meaning.

**I want to abort and go futher**

Let me hit some classics 2d classics:

1.  Sensible World of Soccer
2. Cannon Fodder
3. Mega-Lo-Mania
4. K240
5. Soldat
6. Gravity Force 2
7. Bally 2 (91)
8. Battle of Balls (Chinese (En Jailbreak) clone of Agar.io but man, it is sweet, I had many chinese friends, "xmas4u = :)!" ).  Nice people man and there was broadcasts on TV of it.   

**Can a 2D Performant TypeScript Server be created?**

At the heart of it is how can Vectors travel on the server, and on the client correctly? Airmash does an amazing job of it, I still don't really know what the backup socket does, but it is discussed here: https://www.goodreads.com/book/show/28105277-multiplayer-game-programming  within this book.

I read many books on networking (didn't understand any) but this one made me appreciate Airmash,  yet, it is open ended. 

In order to create a suit of games,  (Airmash being one), what is needed is the "simple" ability to send a particle over the wire that can handle velocity and position.  As soon as that is a real thing, it truely serves as the basis for many games. 

**Hack away on Airmash, but it needs re-written and as engineers, it should be an obtainable goal.**

Thoughts? Insight?

**Comment by derpsderps69** [comment]
Almost every protocol makes a tradeoff between efficiency and semantic richness, and generality.. for example on the extreme side of generality, you just have something like VNC which spits out essentially arrays of pixels, but this would be a nightmare for gaming on anything except a fast LAN

Airmash sits somewhere towards the other extreme.. lots of stuff is implied that doesn't need to be communicated, particles being one of them. Server communicates "explosion" and client handles all the particle rendering itself

I don't know enough about game design to comment much, but definitely there could be room for some kind of generic method for transferring key input from the client, and triggering client actions using some kind of 'macro' messages, that would generalize the way Airmash does things.

Fun to think about, no clue how to approach it though!

**Comment by clark-stevenson** [comment]
Thanks for your insight Derps, I will close this as it doesn't belong here but should anyone be interested or have a plan how to tackle it, give me a shout.
