### ISSUE TITLE
Add colored missiles?

### ISSUE THREAD

**Issue by peace2000** [airmash-refugees/airmash-frontend#27]
Hi, I tried Starmash frontend a bit. They have an option to show missiles as colored, based on the Team color of the shooter.

This actually gives Starmash players a clear advantage over those who play through Airmash.online.

There are situations when countless missiles are flying and it's impossible to keep track who shot every single specific missile on the screen. In Airmash.online, all missiles are grey and I have to dodge every single one, because I cannot always be sure who shot them. In Starmash, those missiles are colored so I always know If I have to dodge them or not.

So, in order to not give Starmash players an advantage, could colored missiles added to Airmash.online as well?

![Näyttökuva (112)](https://user-images.githubusercontent.com/17256841/75120667-c9901400-5695-11ea-9b6b-2cc68dfec14c.png)

This situation in the screenshot is not so complicated, but I have seen many complicated situations where it's a clear advantage to know what missiles you have to dodge and what you don't.

**Comment by BlackCrawler** [comment]
I like how its done in Spatie's client (https://spatiebot.github.io/): missiles of your teammates are shadowed. I think it may be better, you don't need to remember what team you are in, just always ignore shadow missiles.

**Comment by peace2000** [comment]
Yeah, zoom level can affect if missiles are fired off-screen but in situations like someone has taken the flag, the first half of the players is escorting and the second half is trying to shoot him down, there are many players, packed into small area and countless missiles are flying here and there, zoom level doesn't help much. In situations like that, colored/marked missiles are a big deal.

**Comment by congratulatio** [comment]
Colours may need tweaking a bit, but otherwise I think this is now complete.
